"""empty message

Revision ID: f31026900f84
Revises: 2a38c55871b3
Create Date: 2025-03-24 11:41:38.780249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31026900f84'
down_revision = '2a38c55871b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
